refactor release by using bosh-gen replace binaries by source code from github as submodule replace packages script to build go source code add package golang

diff --git a/packages/custom_exporter/packaging b/packages/custom_exporter/packaging
--- a/packages/custom_exporter/packaging
+++ b/packages/custom_exporter/packaging
@@ -1,9 +1,14 @@
 #!/bin/bash
+set -e
 
-set -eux
+mkdir -p ${BOSH_INSTALL_TARGET}/src
+cp -a . ${BOSH_INSTALL_TARGET}/src
+export GOPATH=$BOSH_INSTALL_TARGET
 
-# Extract custom_exporter package
-mkdir -p ${BOSH_INSTALL_TARGET}/bin
-tar xzvf ${BOSH_COMPILE_TARGET}/custom_exporter/custom_exporter-0.2.tar.gz -C ${BOSH_INSTALL_TARGET}/bin/
-chmod +x ${BOSH_INSTALL_TARGET}/bin/custom_exporter
+export GOROOT=$(readlink -nf /var/vcap/packages/golang)
+export PATH=$GOROOT/bin:$PATH
+go install github.com/orange-cloudfoundry/custom_exporter
+
+# clean up source artifacts
+rm -rf ${BOSH_INSTALL_TARGET}/src ${BOSH_INSTALL_TARGET}/pkg
 
